config/routes.rb
Rails.application.routes.draw do
  resources :fighters do
  	resources :skills
    resources :fighter_skills
  end

  root "fighters#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fighter.rb
class Fighter < ApplicationRecord
	validates :first_name, presence: true
	validates :last_name, presence: true
	has_many :fighter_skills
	has_many :skills, through: :fighter_skills
end

app/models/fighter_skill.rb
class FighterSkill < ApplicationRecord
	belongs_to :fighter
  belongs_to :skill
  validates :fighter_id, presence: true
  validates :level, presence: true, numericality: { only_integer: true,
                                    greater_than_or_equal_to: 0,
                                    less_than_or_equal_to: 5 }

  delegate :name, to: :skill
  validate :skills_quantity

  private

	  def skills_quantity
		  fighter = Fighter.find(fighter_id)
		  skills_quantity = fighter.skills.count
			if skills_quantity >= 8
				errors.add(:skills_quantity, "Cannot be more than 9 skills set at the time")
			end
		end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :fighter_skills
  has_many :fighters, through: :fighter_skills
  validates :name, presence: true, length: { maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fighter_skills_controller.rb
class FighterSkillsController < ApplicationController

  def index
    @skills = Skill.all
  end

  def create
    @fighter = Fighter.find(params[:fighter_id])
    fighter_skill.assign_attributes(fighter_skill_params)
    if fighter_skill.save
      redirect_to fighter_path(@fighter)
    else
      render "fighters/show"
    end
  end

  private
    def fighter_skill_params
      params.require(:fighter_skill).permit(:skill_id, :level)
    end

    def fighter_skill
      @fighter_skill ||= existing_fighter_skill.present? ? existing_fighter_skill : new_fighter_skill
    end

    def new_fighter_skill
      fighter_skills_scope.new
    end

    def existing_fighter_skill
      @existing_fighter_skill ||= fighter_skills_scope.where(skill_id: skill_id).first
    end

    def skill_id
      params[:fighter_skill][:skill_id]
    end

    def fighter_skills_scope
      @fighter.fighter_skills
    end
end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  before_action :set_fighter, only: [:show, :edit, :update, :destroy]

  # GET /fighters
  # GET /fighters.json
  def index
    @fighters = Fighter.all
  end

  # GET /fighters/1
  # GET /fighters/1.json
  def show
    @fighter_skill = @fighter.fighter_skills.new
  end

  # GET /fighters/new
  def new
    @fighter = Fighter.new
  end

  # GET /fighters/1/edit
  def edit
  end

  # POST /fighters
  # POST /fighters.json
  def create
    @fighter = Fighter.new(fighter_params)

    respond_to do |format|
      if @fighter.save
        format.html { redirect_to @fighter, notice: 'Fighter was successfully created.' }
        format.json { render :show, status: :created, location: @fighter }
      else
        format.html { render :new }
        format.json { render json: @fighter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fighters/1
  # PATCH/PUT /fighters/1.json
  def update
    respond_to do |format|
      if @fighter.update(fighter_params)
        format.html { redirect_to @fighter, notice: 'Fighter was successfully updated.' }
        format.json { render :show, status: :ok, location: @fighter }
      else
        format.html { render :edit }
        format.json { render json: @fighter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fighters/1
  # DELETE /fighters/1.json
  def destroy
    @fighter.destroy
    respond_to do |format|
      format.html { redirect_to fighters_url, notice: 'Fighter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_skill_to_user
    user = User.find(params[:id])
    user.skills.create(skill_params) #skill name, level...
    @skills_options = Skill.all.map{|s| [ s.name, s.id] }
    #whatever happens when this is is done, redirect, json answer etc...
    if user.skills.update_all(skill_params)
      flash[:success] = "Skill Added"
    else
       render 'add_skill_to_user'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fighter
      @fighter = Fighter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fighter_params
      params.require(:fighter).permit(:first_name, :last_name, :description)
    end

    # Set skills params whitelist    
    def skill_params
      params.permit(:name, :fighter_id)
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fighters_helper.rb
module FightersHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/fighters/_form.html.erb
<%= form_for(fighter) do |f| %>
  <% if fighter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fighter.errors.count, "error") %> prohibited this fighter from being saved:</h2>

      <ul>
      <% fighter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fighters/edit.html.erb
<h1>Editing Fighter</h1>

<%= render 'form', fighter: @fighter %>

<%= link_to 'Show', @fighter %> |
<%= link_to 'Back', fighters_path %>

app/views/fighters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fighters</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fighters.each do |fighter| %>
      <tr>
        <td><%= fighter.first_name %></td>
        <td><%= fighter.last_name %></td>
        <td><%= fighter.description %></td>
        <td><%= link_to 'Show', fighter %></td>
        <td><%= link_to 'Edit', edit_fighter_path(fighter) %></td>
        <td><%= link_to 'Destroy', fighter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fighter', new_fighter_path %>

app/views/fighters/new.html.erb
<h1>New Fighter</h1>

<%= render 'form', fighter: @fighter %>

<%= link_to 'Back', fighters_path %>

app/views/fighters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @fighter.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @fighter.last_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fighter.description %>
</p>

<div class="skills">
  <h3>Skills</h3>
  <% unless @fighter.fighter_skills.where.not(id: nil).empty? %>
    <% @fighter.fighter_skills.where.not(id: nil).each do |s| %>
      <p><%= s.name %>: <%= s.level %></p>
    <% end %>
  <% end %>
  <h4>Add skill</h4>
  <%= form_for([@fighter, @fighter_skill]) do |f| %>
    <p>
      <%= f.label :name %>
      <%= f.select :skill_id, options_from_collection_for_select(Skill.all, :id, :name) %>
    </p>

    <p>
      <%= f.label :level %> (0 - 5)
      <%= f.number_field :level, class: 'form-control' %>
    </p>

    <p>
      <%= f.submit "Add skill", class: "btn btn" %>
    </p>
  <% end %>
</div>

<%= link_to 'Edit', edit_fighter_path(@fighter) %> |
<%= link_to 'Back', fighters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FightClub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>